name:                reasonH
version:             0.1.0.0
github:              "andrewbutterfield/reasonH"
license:             BSD3
author:              "Andrew Butterfield"
maintainer:          "Andrew.Butterfield@scss.tcd.ie"
copyright:           "(c) 2017 Andrew Butterfield"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andrewbutterfield/reasonH#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- containers
- haskeline
- haskell-src

library:
  source-dirs: src

executables:
  hreq:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reasonH
    - haskell-src
    - directory
    - filepath

tests:
  reasonH-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reasonH
